In [ ]:
# Import library
import pandas as pd

In [4]:
# Import dataset
titanic = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"
df = pd.read_csv(titanic)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# Create table contain unique value from survived, pclass, sex, cabin, and embarked field 
categorical_unique_value = {
    'survived': [df['Survived'].unique()],
    'pclass': [df['Pclass'].unique()],
    'sex': [df['Sex'].unique()],
    'cabin': [df['Cabin'].unique()],
    'embarked': [df['Embarked'].unique()],
}

pd.DataFrame(categorical_unique_value).T\
    .rename({0 : 'unique_values'}, axis = 1)

                                              unique_values
survived                                             [0, 1]
pclass                                            [3, 1, 2]
sex                                          [male, female]
cabin     [nan, C85, C123, E46, G6, C103, D56, A6, C23 C...
embarked                                     [S, C, Q, nan]

### Column Details
- `PassengerId`: Passanger Id
- `Survived`: Passanger Survived Status (0 = Not Survived ; 1 = Survived)
- `Pclass`: Passenger Class (1 = Upper/VIP ; 2 = Middle ; 3 = Lower)
- `Name`: Passenger Name
- `Sex`: Passenger Gender (male ; female)
- `Age`: Passenger Age
- `SibSp`: Number of Siblings/Spouses Aboard in The Titanic
- `Parch`: Number of Parents/Children Aboard in The Titanic
- `Ticket`: Ticket Id 
- `Fare`: Ticket Price
- `Cabin`: Passenger Cabin Number 
- `Embarked`: Port of Departure (S = Southampton, C = Cherbourg, Q = Queenstown)

# Task 1 — Eksplorasi awal DataFrame

In [27]:
# Print row and column count
df.shape

(891, 12)

In [28]:
# Print dataframe info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [29]:
# Check null values for each column

df.isnull().sum()\
.sort_values(ascending = False)\
.reset_index()\
.rename(
    {'index':'nama kolom', 0: 'nilai_per_null'},
    axis=1
)

     nama kolom  nilai_per_null
0         Cabin             687
1           Age             177
2      Embarked               2
3   PassengerId               0
4      Survived               0
5        Pclass               0
6          Name               0
7           Sex               0
8         SibSp               0
9         Parch               0
10       Ticket               0
11         Fare               0

In [30]:
# Print statistical summary from numeric column
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

`fare` memiliki nilai minimum dan maksimum yang tidak wajar.
- nilai minimum = 0. Apakah ada penumpang yang tidak bayar tiket ?
- nilai maksimum = 512. Apakah ada penumpang yang bayar berlebih ?

# Task 2 — Querying dengan kondisi majemuk

In [ ]:
# Get passenger count with following condition:
# - Cabin class 1 or 2
# - Age > 30
# - Not Survived (Survived = 0)

df[
    (df['Pclass'].isin([1, 2])) \
      & (df['Age'] > 30) \
      & (df['Survived'] == 0)
]['PassengerId'].count()

np.int64(94)

In [ ]:
# Get passengers with following condition:
# - Female
# - Survived (Survived = 1)
# - Age < 18

df[
    (df['Sex'] == 'female') \
    & (df['Survived'] == 1)\
    & (df['Age'] < 18)
][['Name', 'Age', 'Pclass', 'Embarked']]

                                                  Name    Age  Pclass Embarked
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.00       2        C
10                     Sandstrom, Miss. Marguerite Rut   4.00       3        S
22                         McGowan, Miss. Anna "Annie"  15.00       3        Q
39                         Nicola-Yarred, Miss. Jamila  14.00       3        C
43            Laroche, Miss. Simonne Marie Anne Andree   3.00       2        C
58                        West, Miss. Constance Mirium   5.00       2        S
68                     Andersson, Miss. Erna Alexandra  17.00       3        S
84                                 Ilett, Miss. Bertha  17.00       2        S
156                   Gilnagh, Miss. Katherine "Katie"  16.00       3        Q
172                       Johnson, Miss. Eleanor Ileen   1.00       3        S
184                Kink-Heilmann, Miss. Luise Gretchen   4.00       3        S
208                          Carr, Miss. Helen "Ellen"  16.00       3        Q
233                     Asplund, Miss. Lillian Gertrud   5.00       3        S
237                   Collyer, Miss. Marjorie "Lottie"   8.00       2        S
307  Penasco y Castellana, Mrs. Victor de Satode (M...  17.00       1        C
329                       Hippach, Miss. Jean Gertrude  16.00       1        C
381                        Nakid, Miss. Maria ("Mary")   1.00       3        C
389                              Lehmann, Miss. Bertha  17.00       2        C
435                          Carter, Miss. Lucile Polk  14.00       1        S
446                  Mellinger, Miss. Madeleine Violet  13.00       2        S
448                     Baclini, Miss. Marie Catherine   5.00       3        C
469                      Baclini, Miss. Helene Barbara   0.75       3        C
479                           Hirvonen, Miss. Hildur E   2.00       3        S
504                              Maioni, Miss. Roberta  16.00       1        S
530                           Quick, Miss. Phyllis May   2.00       2        S
535                             Hart, Miss. Eva Miriam   7.00       2        S
618                        Becker, Miss. Marion Louise   4.00       2        S
644                             Baclini, Miss. Eugenie   0.75       3        C
689                  Madill, Miss. Georgette Alexandra  15.00       1        S
691                                 Karun, Miss. Manca   4.00       3        C
720                  Harper, Miss. Annie Jessie "Nina"   6.00       2        S
750                                  Wells, Miss. Joan   4.00       2        S
777                      Emanuel, Miss. Virginia Ethel   5.00       3        S
780                               Ayoub, Miss. Banoura  13.00       3        C
781          Dick, Mrs. Albert Adrian (Vera Gillespie)  17.00       1        S
830            Yasbeck, Mrs. Antoni (Selini Alexander)  15.00       3        C
853                          Lines, Miss. Mary Conover  16.00       1        S
875                   Najib, Miss. Adele Kiamie "Jane"  15.00       3        C

In [ ]:
# Define age classification
# Age <= 12 = "Anak"
# Age 13 - 17 = "Remaja"
# Age 18 - 59 = "Dewasa"
# Age >= 60 = "Lansia" 

df['kelompok_usia'] = pd.cut(df['Age'],
                             bins=[0, 12, 17, 59, max(df['Age'])], 
                             labels=['Anak', 'Remaja', 'Dewasa', 'Lansia'])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,kelompok_usia
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Dewasa
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Dewasa
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Dewasa
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Dewasa
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Dewasa
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Dewasa
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Dewasa
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Dewasa
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Dewasa

# Task 3 — Groupby dan agregasi

In [ ]:
# Calculate survival rate 
# Survival rate = Count of Survived / Total of Passenger

# Get count of survived passenger group by pclass
survived_passenger = df[df['Survived'] == 1][['Pclass','Survived']]\
                        .groupby('Pclass')\
                        .count()

survived_passenger['survival_rate (%)'] = round(survived_passenger['Survived'] / df['Survived'].count(), 2)
survived_passenger

        Survived  survival_rate (%)
Pclass
1            136               0.15
2             87               0.10
3            119               0.13

In [41]:
# Get Age and Fare average group by pclass and sex
df[['Pclass', 'Sex', 'Fare', 'Age']]\
    .groupby(['Pclass', 'Sex'])\
    .agg({'Age':'mean', 'Fare':'mean'})\
    .round({'Age': 0})

                Age        Fare
Pclass Sex
1      female  35.0  106.125798
       male    41.0   67.226127
2      female  29.0   21.970121
       male    31.0   19.741782
3      female  22.0   16.118810
       male    27.0   12.661633

In [42]:
# Get count of pessanger survived / not survived group by kelompok_usia
pd.crosstab(df['kelompok_usia'], df['Survived'])\
    .rename({0:'Not Survived', 1:'Survived'}, axis = 1)

Survived       Not Survived  Survived
kelompok_usia
Anak                     29        40
Remaja                   23        21
Dewasa                  353       222
Lansia                   19         7

# Task 4 — Interpretasi

- Kelas kabin dapat mempengaruhi survival_rate. semakin tinggi kelas kabin maka survival_rate semakin tinggi
- Umur berpengaruh dalam pemilihan kelas kabin. Dimana rata rata umur yang paling tinggi ada di kelas kabin nomor 1 dan rata rata umur paling rendah ada di kelas kabin nomor 2.
- Wanita rata rata membeli tiket lebih mahal dibandingkan pria
- Mayoritas kelompok_usia yang ada dalam kapal adalah Dewasa (Umur 18 - 59)