In [1]:
import pandas as pd

In [3]:
titanic = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"
df = pd.read_csv(titanic)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.groupby(['Sex','Pclass']).agg({'Fare':['min','median','max']})

                  Fare
                   min    median       max
Sex    Pclass
female 1       25.9292  82.66455  512.3292
       2       10.5000  22.00000   65.0000
       3        6.7500  12.47500   69.5500
male   1        0.0000  41.26250  512.3292
       2        0.0000  13.00000   73.5000
       3        0.0000   7.92500   69.5500

In [8]:
pd.crosstab(df['Survived'],df['Pclass'],df['Fare'],aggfunc='mean')

Pclass            1          2          3
Survived
0         64.684007  19.412328  13.669364
1         95.608029  22.055700  13.694887